[package]
name = "reflective_dll"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows-sys.workspace = true
api_hasher = { path = "../../../utils/api_hasher", features = ["hash-crc32"]}

[profile.release]
panic = "abort"