[package]
name = "syscalls"
version = "0.2.0"
edition = "2024"

[dependencies]
api_hasher = { path = "../../utils/api_hasher" }
trampoline = { path = "../../hooking/trampoline" }
windows-sys = { workspace = true }

[features]
default = []
# Enable this to unlock the Win32u strategy
win32u = []